Started to write the drive base
CougarProgramming623/InfiniteRecharge pull request #3
Opened 2020-01-14 22:11 UTC by CarsonH123

Wrote gud code

2020-01-14 22:15 UTC, Mee42 commented
very good I like trains

2020-01-16 00:18 UTC, TroyNeubauer requested changes

2020-01-16 00:18 UTC, TroyNeubauer commented on src/main/cpp/subsystems/DriveTrian.cpp
> +DriveTrain::DriveTrain():m_LeftFront(0), m_RightFront(0), m_LeftBack(0), m_RightBack(0) {
Looks nasty!

2020-01-16 00:21 UTC, TroyNeubauer approved these changes

2020-01-16 00:21 UTC, merged